#!/usr/bin/env node

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const defaultRepository = "justbytes/t3delta";

interface Options {
  readonly version: string;
  readonly assetDir: string;
  readonly outputRoot: string;
  readonly repository: string;
  readonly check: boolean;
}

interface Asset {
  readonly filename: string;
  readonly sha256: string;
}

function parseOptions(argv: readonly string[]): Options {
  let version = "";
  let assetDir = "";
  let outputRoot = repoRoot;
  let repository = defaultRepository;
  let check = false;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    const next = () => {
      const value = argv[i + 1];
      if (!value) throw new Error(`Missing value for ${arg}`);
      i += 1;
      return value;
    };

    if (arg === "--version") version = next();
    else if (arg === "--asset-dir") assetDir = resolve(next());
    else if (arg === "--output-root") outputRoot = resolve(next());
    else if (arg === "--repository") repository = next();
    else if (arg === "--check") check = true;
    else throw new Error(`Unknown argument: ${arg}`);
  }

  if (!/^[0-9]+\.[0-9]+\.[0-9]+(?:[.-][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`Invalid or missing --version: ${version || "<empty>"}`);
  }
  if (!assetDir) throw new Error("Missing --asset-dir");
  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repository)) {
    throw new Error(`Invalid --repository: ${repository}`);
  }

  return { version, assetDir, outputRoot, repository, check };
}

function sha256File(filePath: string): string {
  return createHash("sha256").update(readFileSync(filePath)).digest("hex");
}

function requireAsset(assetDir: string, filename: string): Asset {
  const filePath = resolve(assetDir, filename);
  if (!existsSync(filePath)) {
    throw new Error(`Missing release asset: ${filePath}`);
  }
  return { filename, sha256: sha256File(filePath) };
}

function releaseUrl(repository: string, version: string, filename: string): string {
  return `https://github.com/${repository}/releases/download/v${version}/${filename}`;
}

function writeGeneratedFile(path: string, content: string, check: boolean): void {
  const normalized = content.endsWith("\n") ? content : `${content}\n`;
  if (check) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (current !== normalized) {
      throw new Error(`Generated install manifest is out of date: ${path}`);
    }
    return;
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, normalized);
}

function renderHomebrew(
  version: string,
  repository: string,
  macArm64: Asset,
  macX64: Asset,
): string {
  return `# Generated by scripts/update-install-manifests.ts.
cask "t3-delta" do
  arch arm: "arm64", intel: "x64"

  version "${version}"
  sha256 arm:   "${macArm64.sha256}",
         intel: "${macX64.sha256}"

  url "https://github.com/${repository}/releases/download/v#{version}/T3-Delta-#{version}-#{arch}.dmg",
      verified: "github.com/${repository}/"
  name "T3 Delta"
  desc "Workstation for coding agents"
  homepage "https://github.com/${repository}"

  app "T3 Delta (Alpha).app"
end
`;
}

function renderWingetInstaller(version: string, repository: string, winX64: Asset): string {
  return `# Generated by scripts/update-install-manifests.ts.
PackageIdentifier: Bytes.T3Delta
PackageVersion: ${version}
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ReleaseDate: ${new Date().toISOString().slice(0, 10)}
Installers:
  - Architecture: x64
    InstallerUrl: ${releaseUrl(repository, version, winX64.filename)}
    InstallerSha256: ${winX64.sha256.toUpperCase()}
ManifestType: installer
ManifestVersion: 1.9.0
`;
}

function renderWingetDefaultLocale(version: string, repository: string): string {
  return `# Generated by scripts/update-install-manifests.ts.
PackageIdentifier: Bytes.T3Delta
PackageVersion: ${version}
PackageLocale: en-US
Publisher: Bytes
PackageName: T3 Delta
License: MIT
ShortDescription: Workstation for coding agents.
PackageUrl: https://github.com/${repository}
ManifestType: defaultLocale
ManifestVersion: 1.9.0
`;
}

function renderWingetVersion(version: string): string {
  return `# Generated by scripts/update-install-manifests.ts.
PackageIdentifier: Bytes.T3Delta
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
`;
}

function renderPkgbuild(version: string, repository: string, linuxX64: Asset): string {
  return `# Generated by scripts/update-install-manifests.ts.
pkgname=t3delta-bin
pkgver=${version.replaceAll("-", "_")}
pkgrel=1
pkgdesc="Workstation for coding agents"
arch=("x86_64")
url="https://github.com/${repository}"
license=("MIT")
depends=("fuse2")
options=(!strip)
source_x86_64=("${releaseUrl(repository, version, linuxX64.filename)}")
sha256sums_x86_64=("${linuxX64.sha256}")

package() {
  install -Dm755 "\${srcdir}/${linuxX64.filename}" "\${pkgdir}/opt/t3delta/t3delta.AppImage"
  install -Dm644 /dev/stdin "\${pkgdir}/usr/share/applications/t3delta.desktop" <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=T3 Delta
Comment=Workstation for coding agents
Exec=/opt/t3delta/t3delta.AppImage
Terminal=false
Categories=Development;
DESKTOP
  install -Dm755 /dev/stdin "\${pkgdir}/usr/bin/t3delta" <<'SH'
#!/bin/sh
exec /opt/t3delta/t3delta.AppImage "$@"
SH
}
`;
}

function renderSrcinfo(version: string, repository: string, linuxX64: Asset): string {
  const pkgver = version.replaceAll("-", "_");
  return `# Generated by scripts/update-install-manifests.ts.
pkgbase = t3delta-bin
\tpkgdesc = Workstation for coding agents
\tpkgver = ${pkgver}
\tpkgrel = 1
\turl = https://github.com/${repository}
\tarch = x86_64
\tlicense = MIT
\tdepends = fuse2
\toptions = !strip
\tsource_x86_64 = ${releaseUrl(repository, version, linuxX64.filename)}
\tsha256sums_x86_64 = ${linuxX64.sha256}

pkgname = t3delta-bin
`;
}

export function updateInstallManifests(options: Options): void {
  const macArm64 = requireAsset(options.assetDir, `T3-Delta-${options.version}-arm64.dmg`);
  const macX64 = requireAsset(options.assetDir, `T3-Delta-${options.version}-x64.dmg`);
  const winX64 = requireAsset(options.assetDir, `T3-Delta-${options.version}-x64.exe`);
  const linuxX64 = requireAsset(options.assetDir, `T3-Delta-${options.version}-x64.AppImage`);

  const wingetDir = resolve(
    options.outputRoot,
    "packaging/winget/manifests/b/Bytes/T3Delta",
    options.version,
  );

  writeGeneratedFile(
    resolve(options.outputRoot, "packaging/homebrew/Casks/t3-delta.rb"),
    renderHomebrew(options.version, options.repository, macArm64, macX64),
    options.check,
  );
  writeGeneratedFile(
    resolve(wingetDir, "Bytes.T3Delta.installer.yaml"),
    renderWingetInstaller(options.version, options.repository, winX64),
    options.check,
  );
  writeGeneratedFile(
    resolve(wingetDir, "Bytes.T3Delta.locale.en-US.yaml"),
    renderWingetDefaultLocale(options.version, options.repository),
    options.check,
  );
  writeGeneratedFile(
    resolve(wingetDir, "Bytes.T3Delta.yaml"),
    renderWingetVersion(options.version),
    options.check,
  );
  writeGeneratedFile(
    resolve(options.outputRoot, "packaging/aur/t3delta-bin/PKGBUILD"),
    renderPkgbuild(options.version, options.repository, linuxX64),
    options.check,
  );
  writeGeneratedFile(
    resolve(options.outputRoot, "packaging/aur/t3delta-bin/.SRCINFO"),
    renderSrcinfo(options.version, options.repository, linuxX64),
    options.check,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  updateInstallManifests(parseOptions(process.argv.slice(2)));
}
